module.exports = {
  apps: [
    {
      name: 'vana-backend',
      script: 'uvicorn',
      args: 'app.server:app --reload --port 8000',
      interpreter: 'uv',
      interpreter_args: 'run --env-file .env.local',
      cwd: '/Users/nick/Projects/vana',
      env: {
        NODE_ENV: 'development',
        PYTHONUNBUFFERED: '1',
      },
      watch: false,
      max_memory_restart: '500M',
      error_file: '~/.pm2/logs/vana-backend-error.log',
      out_file: '~/.pm2/logs/vana-backend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'vana-adk',
      script: 'adk',
      args: 'web agents/ --port 8080',
      interpreter: 'uv',
      interpreter_args: 'run --env-file .env.local',
      cwd: '/Users/nick/Projects/vana',
      env: {
        NODE_ENV: 'development',
        PYTHONUNBUFFERED: '1',
      },
      watch: false,
      max_memory_restart: '500M',
      error_file: '~/.pm2/logs/vana-adk-error.log',
      out_file: '~/.pm2/logs/vana-adk-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'vana-frontend',
      script: 'npm',
      args: 'run dev',
      cwd: '/Users/nick/Projects/vana/frontend',
      env: {
        NODE_ENV: 'development',
        PORT: '3000',
      },
      watch: false,
      max_memory_restart: '1G',
      error_file: '~/.pm2/logs/vana-frontend-error.log',
      out_file: '~/.pm2/logs/vana-frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
  ],
};
