#!/bin/bash

# Master script to display launch commands for all documentation agents

echo "🚀 VANA Documentation Agent Launch Commands"
echo "=========================================="
echo ""
echo "Open 4 terminal windows/tabs and run one script in each:"
echo ""
echo "Terminal 1 - Architecture Agent:"
echo "  ./launch_architecture_agent.sh"
echo ""
echo "Terminal 2 - API & Tools Agent:"
echo "  ./launch_api_tools_agent.sh"
echo ""
echo "Terminal 3 - Deployment Agent:"
echo "  ./launch_deployment_agent.sh"
echo ""
echo "Terminal 4 - User Guide Agent:"
echo "  ./launch_user_guide_agent.sh"
echo ""
echo "⚠️  IMPORTANT: Run each script in a SEPARATE terminal!"
echo ""
echo "After each agent starts, remember to:"
echo "1. Run /config"
echo "2. Run /memory-status"
echo "3. Paste the prompt from INITIAL_PROMPT.md"
echo ""
echo "Happy documenting! 📝"