/**
 * Centralized error identifiers for consistent error tracking and monitoring.
 *
 * Naming convention: COMPONENT_ACTION_RESULT
 * Example: CACHE_BUST_RELOAD_FAILED
 */

export const ERROR_IDS = {
  // Cache-related errors
  CACHE_BUST_RELOAD_FAILED: 'CACHE_BUST_RELOAD_FAILED',
  CACHE_CLEAR_FAILED: 'CACHE_CLEAR_FAILED',

  // Service Worker errors
  SERVICE_WORKER_UPDATE_CHECK_FAILED: 'SERVICE_WORKER_UPDATE_CHECK_FAILED',
  SERVICE_WORKER_POST_MESSAGE_FAILED: 'SERVICE_WORKER_POST_MESSAGE_FAILED',
  SERVICE_WORKER_SETUP_FAILED: 'SERVICE_WORKER_SETUP_FAILED',

  // Streaming errors
  STREAM_FAILED: 'STREAM_FAILED',
  STREAM_CANCEL_FAILED: 'STREAM_CANCEL_FAILED',

  // Message errors
  MESSAGE_RETRY_FAILED: 'MESSAGE_RETRY_FAILED',
  MESSAGE_SAVE_FAILED: 'MESSAGE_SAVE_FAILED',
  MESSAGE_COMPARISON_FAILED: 'MESSAGE_COMPARISON_FAILED',
  MESSAGE_LIST_SCROLL_FAILED: 'MESSAGE_LIST_SCROLL_FAILED',

  // File upload errors
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',

  // Clipboard errors
  CLIPBOARD_COPY_FAILED: 'CLIPBOARD_COPY_FAILED',

  // Artifact errors
  ARTIFACT_RENDER_TIMEOUT: 'ARTIFACT_RENDER_TIMEOUT',
  ARTIFACT_BUNDLE_RETRY_FAILED: 'ARTIFACT_BUNDLE_RETRY_FAILED',
} as const;

export type ErrorId = typeof ERROR_IDS[keyof typeof ERROR_IDS];
