export const ERROR_IDS = {
  // Streaming errors
  STREAM_FAILED: 'STREAM_FAILED',
  STREAM_CANCEL_FAILED: 'STREAM_CANCEL_FAILED',

  // Message errors
  MESSAGE_RETRY_FAILED: 'MESSAGE_RETRY_FAILED',
  MESSAGE_SAVE_FAILED: 'MESSAGE_SAVE_FAILED',
  MESSAGE_COMPARISON_FAILED: 'MESSAGE_COMPARISON_FAILED',
  MESSAGE_LIST_SCROLL_FAILED: 'MESSAGE_LIST_SCROLL_FAILED',

  // File upload errors
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',

  // Clipboard errors
  CLIPBOARD_COPY_FAILED: 'CLIPBOARD_COPY_FAILED',

  // Artifact errors
  ARTIFACT_RENDER_TIMEOUT: 'ARTIFACT_RENDER_TIMEOUT',
  ARTIFACT_BUNDLE_RETRY_FAILED: 'ARTIFACT_BUNDLE_RETRY_FAILED',
} as const;
