export const ERROR_IDS = {
  // Streaming errors
  STREAM_FAILED: 'STREAM_FAILED',
  STREAM_CANCEL_FAILED: 'STREAM_CANCEL_FAILED',

  // Message errors
  MESSAGE_RETRY_FAILED: 'MESSAGE_RETRY_FAILED',
  MESSAGE_SAVE_FAILED: 'MESSAGE_SAVE_FAILED',
  MESSAGE_COMPARISON_FAILED: 'MESSAGE_COMPARISON_FAILED',
  MESSAGE_LIST_SCROLL_FAILED: 'MESSAGE_LIST_SCROLL_FAILED',

  // File upload errors
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',

  // Clipboard errors
  CLIPBOARD_COPY_FAILED: 'CLIPBOARD_COPY_FAILED',

  // Artifact errors
  ARTIFACT_RENDER_TIMEOUT: 'ARTIFACT_RENDER_TIMEOUT',
  ARTIFACT_BUNDLE_RETRY_FAILED: 'ARTIFACT_BUNDLE_RETRY_FAILED',
  ARTIFACT_SAVE_FAILED: 'ARTIFACT_SAVE_FAILED',

  // Version check errors
  VERSION_CHECK_ERROR: 'VERSION_CHECK_ERROR',
  VERSION_CHECK_UNHANDLED: 'VERSION_CHECK_UNHANDLED',

  // Skills System v2 Error IDs
  SKILL_DETECTION_UNAVAILABLE: 'SKILL_DETECTION_UNAVAILABLE',
  SKILL_DETECTION_API_ERROR: 'SKILL_DETECTION_API_ERROR',
  SKILL_DETECTION_BUG: 'SKILL_DETECTION_BUG',
  SKILL_DETECTION_FAILED: 'SKILL_DETECTION_FAILED',
  SKILL_DETECTION_EMPTY: 'SKILL_DETECTION_EMPTY',
  SKILL_DETECTION_PARSE_ERROR: 'SKILL_DETECTION_PARSE_ERROR',
  SKILL_DETECTION_NO_API_KEY: 'SKILL_DETECTION_NO_API_KEY',
  SKILL_SYSTEM_ERROR: 'SKILL_SYSTEM_ERROR',
  SKILL_PROVIDER_FAILED: 'SKILL_PROVIDER_FAILED',
  SKILL_DETECTION_CONTINUATION_ERROR: 'SKILL_DETECTION_CONTINUATION_ERROR',
  SKILL_DETECTION_NO_CONTENT: 'SKILL_DETECTION_NO_CONTENT',
  ACTION_EXECUTION_BUG: 'ACTION_EXECUTION_BUG',
  ACTION_EXECUTION_ERROR: 'ACTION_EXECUTION_ERROR',
  TOOL_EXECUTION_FAILED: 'TOOL_EXECUTION_FAILED',
  GEMINI_CONTINUATION_ERROR: 'GEMINI_CONTINUATION_ERROR',
  GEMINI_NO_CONTENT: 'GEMINI_NO_CONTENT',
} as const;

export type ErrorId = typeof ERROR_IDS[keyof typeof ERROR_IDS];
