# Automated cleanup workflow for 1GB Digital Ocean droplet
# Runs weekly to prevent storage/memory issues

name: Resource Cleanup

on:
  schedule:
    # Run every Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:  # Allow manual triggering

jobs:
  cleanup-runner:
    runs-on: self-hosted
    steps:
      - name: System cleanup
        run: |
          echo "Starting system cleanup..."
          
          # Clean Docker system
          docker system prune -af --volumes
          
          # Remove old GitHub Actions artifacts locally
          rm -rf /tmp/actions-runner-* || true
          rm -rf /home/runner/actions-runner/_work/_temp/* || true
          
          # Clean package caches
          rm -rf ~/.cache/uv || true
          rm -rf ~/.cache/pip || true
          rm -rf /tmp/pip-* || true
          
          # Clean old log files
          sudo find /var/log -name "*.log" -type f -mtime +7 -delete || true
          
          # Clean apt cache
          sudo apt-get clean || true
          sudo apt-get autoremove -y || true
          
          echo "Cleanup completed"
      
      - name: System status report
        run: |
          echo "=== System Status Report ==="
          echo "Memory usage:"
          free -h
          echo ""
          echo "Disk usage:"
          df -h
          echo ""
          echo "Docker images:"
          docker images --format "table {{.Repository}}:{{.Tag}}\t{{.Size}}\t{{.CreatedAt}}"
          echo ""
          echo "Docker containers:"
          docker ps -a --format "table {{.Names}}\t{{.Status}}\t{{.Size}}"
      
      - name: Alert if low resources
        run: |
          # Check if available memory is less than 200MB
          AVAILABLE_MEM=$(free -m | awk 'NR==2{printf "%.0f", $7}')
          if [ $AVAILABLE_MEM -lt 200 ]; then
            echo "⚠️ Warning: Low memory available: ${AVAILABLE_MEM}MB"
          fi
          
          # Check if root partition is more than 80% full
          DISK_USAGE=$(df / | awk 'NR==2{print $5}' | sed 's/%//')
          if [ $DISK_USAGE -gt 80 ]; then
            echo "⚠️ Warning: Disk usage high: ${DISK_USAGE}%"
          fi

  cleanup-ghcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Delete old container images
        uses: actions/github-script@v6
        with:
          script: |
            const package_name = context.repo.repo.toLowerCase();
            const owner = context.repo.owner;
            
            try {
              // Get all versions of the package
              const versions = await github.rest.packages.getAllPackageVersionsForPackageOwnedByOrg({
                package_type: 'container',
                package_name: package_name,
                org: owner,
                per_page: 100
              });
              
              // Keep the latest 5 versions, delete the rest
              const versionsToDelete = versions.data.slice(5);
              
              for (const version of versionsToDelete) {
                if (version.metadata && version.metadata.container && version.metadata.container.tags.length === 0) {
                  // Delete untagged versions
                  await github.rest.packages.deletePackageVersionForOrg({
                    package_type: 'container',
                    package_name: package_name,
                    org: owner,
                    package_version_id: version.id
                  });
                  console.log(`Deleted version ${version.id}`);
                }
              }
            } catch (error) {
              console.log(`Error cleaning up packages: ${error.message}`);
              // Don't fail the workflow if cleanup fails
            }