apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vana-dev
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 900
      serviceAccountName: 960076421399-compute@developer.gserviceaccount.com
      containers:
      - image: gcr.io/analystai-454200/cloud-run-source-deploy/vana-dev@sha256:e7edbcef66b87becd6c72e14f50e1c19f1fe5a4a89033c965e9f71a0f18cf1a0
        ports:
        - containerPort: 8081
        env:
        - name: GOOGLE_API_KEY
          value: "AIzaSyDYIDD4C_kDY9DF0UdzIRv7kdCH1xloAp0"
        - name: ENVIRONMENT
          value: "development"
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
  traffic:
  - percent: 100
    latestRevision: true