# VANA Enhanced Cloud Build Configuration with Versioning
# Includes enhanced reasoning capabilities and comprehensive version tracking

steps:
  # Set up build environment and extract version information
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=== VANA Enhanced Build Started ==="
        echo "Commit: $(git rev-parse --short HEAD)"
        echo "Branch: $(git rev-parse --abbrev-ref HEAD)"
        echo "Build ID: $BUILD_ID"
        echo "Project: $PROJECT_ID"
        
        # Export version info for subsequent steps
        export COMMIT_SHA=$(git rev-parse HEAD)
        export COMMIT_SHORT=$(git rev-parse --short HEAD)
        export BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
        export BUILD_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        
        echo "COMMIT_SHA=$COMMIT_SHA" >> /workspace/build.env
        echo "COMMIT_SHORT=$COMMIT_SHORT" >> /workspace/build.env
        echo "BRANCH_NAME=$BRANCH_NAME" >> /workspace/build.env
        echo "BUILD_TIMESTAMP=$BUILD_TIMESTAMP" >> /workspace/build.env
        echo "ENHANCED_REASONING_VERSION=1.0.0" >> /workspace/build.env
        
        # Make variables available to Cloud Build
        echo "COMMIT_SHA: $COMMIT_SHA"
        echo "COMMIT_SHORT: $COMMIT_SHORT"
        echo "BRANCH_NAME: $BRANCH_NAME"
        
        echo "=== Version Environment Prepared ==="

  # Build Docker image with enhanced tagging
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/build.env
        
        echo "=== Building Enhanced VANA Image ==="
        echo "Image tags:"
        echo "  - gcr.io/$PROJECT_ID/vana-enhanced:$COMMIT_SHORT"
        echo "  - gcr.io/$PROJECT_ID/vana-enhanced:latest"
        echo "  - gcr.io/$PROJECT_ID/vana-enhanced:build-$BUILD_ID"
        
        # Build with multiple tags for better traceability
        docker build \
          -f deployment/Dockerfile \
          -t gcr.io/$PROJECT_ID/vana-enhanced:$COMMIT_SHORT \
          -t gcr.io/$PROJECT_ID/vana-enhanced:latest \
          -t gcr.io/$PROJECT_ID/vana-enhanced:build-$BUILD_ID \
          --build-arg BUILD_ID=$BUILD_ID \
          --build-arg COMMIT_SHA=$COMMIT_SHA \
          --build-arg BUILD_TIMESTAMP=$BUILD_TIMESTAMP \
          --build-arg ENHANCED_REASONING=true \
          --cache-from gcr.io/$PROJECT_ID/vana-enhanced:latest \
          .

  # Push all image tags
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/build.env
        
        echo "=== Pushing Enhanced VANA Images ==="
        docker push gcr.io/$PROJECT_ID/vana-enhanced:$COMMIT_SHORT
        docker push gcr.io/$PROJECT_ID/vana-enhanced:latest
        docker push gcr.io/$PROJECT_ID/vana-enhanced:build-$BUILD_ID
        
        echo "Images pushed successfully"

  # Deploy to development environment with enhanced configuration
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/build.env
        
        echo "=== Deploying Enhanced VANA to Development ==="
        echo "Service: vana-enhanced-dev"
        echo "Image: gcr.io/$PROJECT_ID/vana-enhanced:$COMMIT_SHORT"
        echo "Enhanced Reasoning: Enabled"
        
        gcloud run deploy vana-enhanced-dev \
          --image=gcr.io/$PROJECT_ID/vana-enhanced:$COMMIT_SHORT \
          --platform=managed \
          --region=us-central1 \
          --allow-unauthenticated \
          --memory=4Gi \
          --cpu=2 \
          --min-instances=0 \
          --max-instances=10 \
          --concurrency=50 \
          --timeout=900 \
          --service-account=vana-vector-search-sa@$PROJECT_ID.iam.gserviceaccount.com \
          --port=8000 \
          --set-env-vars="ENVIRONMENT=development,GOOGLE_GENAI_USE_VERTEXAI=true,GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_LOCATION=us-central1,GOOGLE_CLOUD_REGION=us-central1,VANA_MODEL=gemini-2.0-flash,LOG_LEVEL=INFO,BUILD_ID=$BUILD_ID,BUILD_NUMBER=$BUILD_ID,BUILD_TIMESTAMP=$BUILD_TIMESTAMP,COMMIT_SHA=$COMMIT_SHA,BRANCH_NAME=$BRANCH_NAME,BUILDER=cloud-build,ENHANCED_REASONING_ENABLED=true,REASONING_TOOLS_COUNT=5,DASHBOARD_ENABLED=true,RAG_CORPUS_RESOURCE_NAME=projects/$PROJECT_ID/locations/us-central1/ragCorpora/2305843009213693952" \
          --set-secrets="BRAVE_API_KEY=brave-api-key:latest,OPENROUTER_API_KEY=openrouter-api-key:latest"
        
        echo "=== Deployment Completed ==="

  # Generate and save version manifest
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/build.env
        
        echo "=== Generating Version Manifest ==="
        
        # Create comprehensive version manifest
        cat > version_manifest.json << EOF
        {
          "version": "1.0.0-$COMMIT_SHORT",
          "base_version": "1.0.0",
          "git": {
            "commit_hash": "$COMMIT_SHA",
            "commit_short": "$COMMIT_SHORT",
            "branch": "$BRANCH_NAME",
            "commit_message": "$(git log -1 --pretty=%B | head -1)",
            "commit_timestamp": "$(git log -1 --pretty=%cI)"
          },
          "build": {
            "build_id": "$BUILD_ID",
            "build_number": "$BUILD_ID",
            "build_timestamp": "$BUILD_TIMESTAMP",
            "builder": "cloud-build",
            "project_id": "$PROJECT_ID",
            "region": "us-central1",
            "environment": "development"
          },
          "deployment": {
            "timestamp": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
            "environment": "development",
            "region": "us-central1",
            "service_name": "vana-enhanced-dev",
            "image": "gcr.io/$PROJECT_ID/vana-enhanced:$COMMIT_SHORT"
          },
          "enhanced_features": {
            "reasoning_tools": 5,
            "mathematical_reasoning": true,
            "logical_reasoning": true,
            "enhanced_echo": true,
            "enhanced_task_analysis": true,
            "reasoning_coordination": true,
            "integration_commit": "$COMMIT_SHA"
          }
        }
        EOF
        
        echo "Version manifest generated:"
        cat version_manifest.json
        
        # Store in Cloud Storage for later retrieval
        gsutil cp version_manifest.json gs://$PROJECT_ID-vana-builds/manifests/build-$BUILD_ID-manifest.json
        gsutil cp version_manifest.json gs://$PROJECT_ID-vana-builds/manifests/latest-manifest.json
        
        echo "Version manifest stored in Cloud Storage"

  # Validate deployment and enhanced features
  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=== Validating Enhanced VANA Deployment ==="
        
        # Wait for deployment to be ready
        sleep 30
        
        # Get service URL
        SERVICE_URL=$(gcloud run services describe vana-enhanced-dev \
          --region=us-central1 \
          --format='value(status.url)')
        
        echo "Service URL: $SERVICE_URL"
        
        # Test health endpoint
        echo "Testing health endpoint..."
        curl -f "$SERVICE_URL/health" || echo "Health check failed"
        
        # Test info endpoint with enhanced features
        echo "Testing info endpoint with enhanced features..."
        INFO_RESPONSE=$(curl -s "$SERVICE_URL/info")
        echo "Info response: $INFO_RESPONSE"
        
        # Validate enhanced reasoning features are present
        if echo "$INFO_RESPONSE" | grep -q "enhanced_features"; then
          echo "✅ Enhanced features detected in deployment"
        else
          echo "❌ Enhanced features not found in deployment"
          exit 1
        fi
        
        if echo "$INFO_RESPONSE" | grep -q "reasoning_tools.*5"; then
          echo "✅ All 5 reasoning tools confirmed"
        else
          echo "❌ Reasoning tools count incorrect"
          exit 1
        fi
        
        echo "=== Enhanced VANA Deployment Validation Successful ==="

# Container images to be pushed to registry
images:
  - 'gcr.io/${PROJECT_ID}/vana-enhanced:${COMMIT_SHA}'
  - 'gcr.io/${PROJECT_ID}/vana-enhanced:latest'

# Substitutions for dynamic values
substitutions:
  _SERVICE_NAME: 'vana-enhanced-dev'
  _REGION: 'us-central1'
  _MEMORY: '4Gi'
  _CPU: '2'
  _MAX_INSTANCES: '10'

# Build options for optimization
options:
  # Use high-performance machine type
  machineType: 'E2_HIGHCPU_8'
  # Enable Docker layer caching
  env:
    - 'DOCKER_BUILDKIT=1'
  # Increase disk size for enhanced reasoning dependencies
  diskSizeGb: 120
  # Use substitution for dynamic values
  substitution_option: 'ALLOW_LOOSE'
  # Enhanced logging for better debugging
  logging: 'CLOUD_LOGGING_ONLY'

# Extended timeout for enhanced build with validation
timeout: '1200s'