# Simple Enhanced VANA Cloud Build - Based on working cloudbuild-dev.yaml
# Includes enhanced reasoning validation with minimal complexity

steps:
  # Build the enhanced container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build' 
      - '-t' 
      - 'gcr.io/$PROJECT_ID/vana-enhanced-dev:latest'
      - '-f' 
      - 'deployment/Dockerfile' 
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vana-enhanced-dev:latest']
  
  # Deploy enhanced container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'vana-enhanced-dev'
      - '--image'
      - 'gcr.io/$PROJECT_ID/vana-enhanced-dev:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      - '--concurrency'
      - '50'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--timeout'
      - '900'
      - '--service-account'
      - 'vana-vector-search-sa@$PROJECT_ID.iam.gserviceaccount.com'
      - '--port'
      - '8000'
      - '--set-env-vars'
      - 'ENVIRONMENT=development,GOOGLE_GENAI_USE_VERTEXAI=true,GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_LOCATION=us-central1,GOOGLE_CLOUD_REGION=us-central1,VANA_MODEL=gemini-2.0-flash,LOG_LEVEL=INFO,ENHANCED_REASONING_ENABLED=true,REASONING_TOOLS_COUNT=5,DASHBOARD_ENABLED=true,RAG_CORPUS_RESOURCE_NAME=projects/$PROJECT_ID/locations/us-central1/ragCorpora/2305843009213693952'
      - '--set-secrets'
      - 'BRAVE_API_KEY=brave-api-key:latest,OPENROUTER_API_KEY=openrouter-api-key:latest'

  # Validate enhanced features are working
  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "=== Validating Enhanced VANA Deployment ==="
        
        # Wait for deployment to be ready
        sleep 30
        
        # Get service URL
        SERVICE_URL=$(gcloud run services describe vana-enhanced-dev \
          --region=us-central1 \
          --format='value(status.url)')
        
        echo "Service URL: $SERVICE_URL"
        
        # Test health endpoint
        echo "Testing health endpoint..."
        curl -f "$SERVICE_URL/health" || echo "Health check failed"
        
        # Test enhanced features
        echo "Testing enhanced features..."
        INFO_RESPONSE=$(curl -s "$SERVICE_URL/info")
        echo "Info response received"
        
        # Validate enhanced reasoning features are present
        if echo "$INFO_RESPONSE" | grep -q "enhanced_features"; then
          echo "✅ Enhanced features detected in deployment"
        else
          echo "❌ Enhanced features not found in deployment"
          exit 1
        fi
        
        if echo "$INFO_RESPONSE" | grep -q "reasoning_tools.*5"; then
          echo "✅ All 5 reasoning tools confirmed"
        else
          echo "❌ Reasoning tools count incorrect"
          exit 1
        fi
        
        echo "=== Enhanced VANA Deployment Validation Successful ==="

images:
  - 'gcr.io/$PROJECT_ID/vana-enhanced-dev:latest'

timeout: '900s'