steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/vana-dev:$COMMIT_SHA', '-f', 'deployment/Dockerfile', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/vana-dev:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'vana-dev'
      - '--image'
      - 'gcr.io/$PROJECT_ID/vana-dev:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--concurrency'
      - '40'
      - '--max-instances'
      - '5'
      - '--min-instances'
      - '0'
      - '--timeout'
      - '600'
      - '--set-env-vars'
      - 'ENVIRONMENT=development'
      - '--set-env-vars'
      - 'GOOGLE_GENAI_USE_VERTEXAI=true'

images:
  - 'gcr.io/$PROJECT_ID/vana-dev:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_4'

timeout: '900s'
