#!/bin/bash

# Script to setup Claude Code user-level permissions for auto-approval
# This will configure ~/.claude/settings.json with comprehensive auto-approvals

echo "🔧 Setting up Claude Code user-level permissions..."

# Create the ~/.claude directory if it doesn't exist
mkdir -p ~/.claude

# Check if user settings already exist
if [ -f ~/.claude/settings.json ]; then
    echo "📋 Backing up existing user settings to ~/.claude/settings.json.backup"
    cp ~/.claude/settings.json ~/.claude/settings.json.backup
fi

# Create comprehensive user settings with auto-approvals
cat > ~/.claude/settings.json << 'EOF'
{
  "permissions": {
    "allow": [
      "Bash(npx claude-flow *)",
      "Bash(npm *)",
      "Bash(npx *)",
      "Bash(yarn *)",
      "Bash(pnpm *)",
      "Bash(git *)",
      "Bash(gh *)",
      "Bash(python *)",
      "Bash(python3 *)",
      "Bash(pip *)",
      "Bash(pip3 *)",
      "Bash(uv *)",
      "Bash(pytest *)",
      "Bash(ruff *)",
      "Bash(black *)",
      "Bash(mypy *)",
      "Bash(flake8 *)",
      "Bash(isort *)",
      "Bash(make *)",
      "Bash(cat *)",
      "Bash(ls *)",
      "Bash(find *)",
      "Bash(grep *)",
      "Bash(rg *)",
      "Bash(sed *)",
      "Bash(awk *)",
      "Bash(sort *)",
      "Bash(uniq *)",
      "Bash(wc *)",
      "Bash(head *)",
      "Bash(tail *)",
      "Bash(tree *)",
      "Bash(mkdir *)",
      "Bash(mv *)",
      "Bash(cp *)",
      "Bash(touch *)",
      "Bash(chmod *)",
      "Bash(ps *)",
      "Bash(kill *)",
      "Bash(pkill *)",
      "Bash(lsof *)",
      "Bash(netstat *)",
      "Bash(ss *)",
      "Bash(df *)",
      "Bash(du *)",
      "Bash(free *)",
      "Bash(curl *)",
      "Bash(wget *)",
      "Bash(ping *)",
      "Bash(docker *)",
      "Bash(docker-compose *)",
      "Bash(gcloud *)",
      "Bash(terraform *)",
      "Bash(kubectl *)",
      "Bash(helm *)",
      "Bash(source *)",
      "Bash(export *)",
      "Bash(echo *)",
      "Bash(printf *)",
      "Bash(test *)",
      "Bash([ *)",
      "Bash([[ *)",
      "Bash(tar *)",
      "Bash(zip *)",
      "Bash(unzip *)",
      "Bash(gzip *)",
      "Bash(gunzip *)",
      "Bash(jq *)",
      "Bash(yq *)",
      "Bash(diff *)",
      "Bash(patch *)",
      "Bash(date)",
      "Bash(whoami)",
      "Bash(pwd)",
      "Bash(hostname)",
      "Bash(uname *)",
      "Bash(which *)",
      "Bash(whereis *)",
      "Bash(type *)",
      "Bash(env)",
      "Bash(clear)",
      "Bash(reset)",
      "Bash(apt *)",
      "Bash(apt-get *)",
      "Bash(brew *)",
      "Bash(code *)",
      "Bash(open *)",
      "Bash(xdg-open *)",
      "Bash(cd *)",
      "Bash(pushd *)",
      "Bash(popd *)",
      "Bash(dirs *)",
      "Bash(history *)",
      "Bash(alias *)",
      "Bash(unset *)",
      "Bash(ln *)",
      "Bash(readlink *)",
      "Bash(realpath *)",
      "Bash(basename *)",
      "Bash(dirname *)",
      "Bash(vim *)",
      "Bash(vi *)",
      "Bash(nano *)",
      "Bash(emacs *)",
      "Bash(pbcopy *)",
      "Bash(pbpaste *)",
      "Bash(xargs *)",
      "Bash(tee *)",
      "Bash(watch *)",
      "Bash(time *)",
      "Bash(sleep *)",
      "Bash(wait *)",
      "Bash(jobs *)",
      "Bash(fg *)",
      "Bash(bg *)",
      "Bash(nohup *)",
      "Bash(screen *)",
      "Bash(tmux *)",
      "Bash(ssh *)",
      "Bash(scp *)",
      "Bash(rsync *)",
      "Bash(ftp *)",
      "Bash(sftp *)",
      "Bash(traceroute *)",
      "Bash(nslookup *)",
      "Bash(dig *)",
      "Bash(host *)",
      "Bash(ifconfig *)",
      "Bash(ip *)",
      "Bash(route *)",
      "Bash(iptables *)",
      "Bash(systemctl *)",
      "Bash(service *)",
      "Bash(journalctl *)",
      "Bash(dmesg *)",
      "Bash(mount *)",
      "Bash(umount *)",
      "Bash(lsblk *)",
      "Bash(blkid *)",
      "Bash(id *)",
      "Bash(groups *)",
      "Bash(users *)",
      "Bash(who *)",
      "Bash(w *)",
      "Bash(last *)",
      "Bash(su *)",
      "Bash(sudo *)",
      "Bash(passwd *)",
      "Bash(useradd *)",
      "Bash(usermod *)",
      "Bash(groupadd *)",
      "Bash(groupmod *)",
      "Bash(chgrp *)",
      "Bash(chown *)",
      "Bash(umask *)",
      "Bash(setfacl *)",
      "Bash(getfacl *)",
      "Bash(locale *)",
      "Bash(timedatectl *)",
      "Bash(cal *)",
      "Bash(bc *)",
      "Bash(expr *)",
      "Bash(seq *)",
      "Bash(shuf *)",
      "Bash(od *)",
      "Bash(hexdump *)",
      "Bash(xxd *)",
      "Bash(strings *)",
      "Bash(file *)",
      "Bash(stat *)",
      "Bash(md5sum *)",
      "Bash(sha1sum *)",
      "Bash(sha256sum *)",
      "Bash(sha512sum *)",
      "Bash(base64 *)",
      "Bash(openssl *)",
      "Bash(gpg *)",
      "Bash(yum *)",
      "Bash(dnf *)",
      "Bash(snap *)",
      "Bash(flatpak *)",
      "Bash(rpm *)",
      "Bash(dpkg *)",
      "Bash(pkg *)",
      "Bash(pacman *)",
      "Bash(zypper *)",
      "Bash(emerge *)",
      "Bash(port *)",
      "Bash(cargo *)",
      "Bash(rustc *)",
      "Bash(go *)",
      "Bash(java *)",
      "Bash(javac *)",
      "Bash(mvn *)",
      "Bash(gradle *)",
      "Bash(ant *)",
      "Bash(ruby *)",
      "Bash(gem *)",
      "Bash(bundle *)",
      "Bash(rake *)",
      "Bash(perl *)",
      "Bash(cpan *)",
      "Bash(php *)",
      "Bash(composer *)",
      "Bash(dotnet *)",
      "Bash(nuget *)",
      "Bash(swift *)",
      "Bash(swiftc *)",
      "Bash(kotlin *)",
      "Bash(kotlinc *)",
      "Bash(scala *)",
      "Bash(scalac *)",
      "Bash(sbt *)",
      "Bash(clang *)",
      "Bash(clang++ *)",
      "Bash(gcc *)",
      "Bash(g++ *)",
      "Bash(cmake *)",
      "Bash(automake *)",
      "Bash(autoconf *)",
      "Bash(./configure *)",
      "Bash(ldconfig *)",
      "Bash(ldd *)",
      "Bash(nm *)",
      "Bash(objdump *)",
      "Bash(readelf *)",
      "Bash(strace *)",
      "Bash(ltrace *)",
      "Bash(gdb *)",
      "Bash(lldb *)",
      "Bash(valgrind *)",
      "Bash(perf *)",
      "Bash(sar *)",
      "Bash(iostat *)",
      "Bash(vmstat *)",
      "Bash(mpstat *)",
      "Bash(pidstat *)",
      "Bash(iotop *)",
      "Bash(iftop *)",
      "Bash(nethogs *)",
      "Bash(tcpdump *)",
      "Bash(wireshark *)",
      "Bash(tshark *)",
      "Bash(nmap *)",
      "Bash(nc *)",
      "Bash(netcat *)",
      "Bash(telnet *)",
      "Bash(socat *)",
      "Bash(certbot *)",
      "Bash(acme.sh *)",
      "Bash(nginx *)",
      "Bash(apache2 *)",
      "Bash(httpd *)",
      "Bash(mysql *)",
      "Bash(mysqldump *)",
      "Bash(psql *)",
      "Bash(pg_dump *)",
      "Bash(redis-cli *)",
      "Bash(mongo *)",
      "Bash(mongodump *)",
      "Bash(sqlite3 *)",
      "Bash(influx *)",
      "Bash(cassandra *)",
      "Bash(cqlsh *)",
      "Bash(elasticsearch *)",
      "Bash(kibana *)",
      "Bash(logstash *)",
      "Bash(filebeat *)",
      "Bash(metricbeat *)",
      "Bash(prometheus *)",
      "Bash(grafana *)",
      "Bash(ansible *)",
      "Bash(ansible-playbook *)",
      "Bash(puppet *)",
      "Bash(chef *)",
      "Bash(salt *)",
      "Bash(vagrant *)",
      "Bash(packer *)",
      "Bash(minikube *)",
      "Bash(kind *)",
      "Bash(k3s *)",
      "Bash(k3d *)",
      "Bash(kubeadm *)",
      "Bash(kubelet *)",
      "Bash(kustomize *)",
      "Bash(skaffold *)",
      "Bash(istioctl *)",
      "Bash(linkerd *)",
      "Bash(consul *)",
      "Bash(vault *)",
      "Bash(nomad *)",
      "Bash(etcd *)",
      "Bash(etcdctl *)",
      "Bash(aws *)",
      "Bash(az *)",
      "Bash(gsutil *)",
      "Bash(bq *)",
      "Bash(firebase *)",
      "Bash(heroku *)",
      "Bash(vercel *)",
      "Bash(netlify *)",
      "Bash(fly *)",
      "Bash(railway *)",
      "Bash(render *)",
      "Bash(supabase *)",
      "Bash(prisma *)",
      "Bash(sequelize *)",
      "Bash(typeorm *)",
      "Bash(knex *)",
      "Bash(migrate *)",
      "Bash(flask *)",
      "Bash(django-admin *)",
      "Bash(rails *)",
      "Bash(artisan *)",
      "Bash(wp *)",
      "Bash(drush *)",
      "Bash(gatsby *)",
      "Bash(next *)",
      "Bash(nuxt *)",
      "Bash(vue *)",
      "Bash(ng *)",
      "Bash(create-react-app *)",
      "Bash(vite *)",
      "Bash(webpack *)",
      "Bash(parcel *)",
      "Bash(rollup *)",
      "Bash(esbuild *)",
      "Bash(tsc *)",
      "Bash(tsx *)",
      "Bash(ts-node *)",
      "Bash(babel *)",
      "Bash(eslint *)",
      "Bash(prettier *)",
      "Bash(stylelint *)",
      "Bash(jest *)",
      "Bash(mocha *)",
      "Bash(chai *)",
      "Bash(jasmine *)",
      "Bash(karma *)",
      "Bash(cypress *)",
      "Bash(playwright *)",
      "Bash(puppeteer *)",
      "Bash(selenium *)",
      "Bash(webdriver *)",
      "Bash(protractor *)",
      "Bash(nightwatch *)",
      "Bash(testcafe *)",
      "Bash(detox *)",
      "Bash(appium *)",
      "Bash(expo *)",
      "Bash(react-native *)",
      "Bash(flutter *)",
      "Bash(dart *)",
      "Bash(pod *)",
      "Bash(carthage *)",
      "Bash(fastlane *)",
      "Bash(xcodebuild *)",
      "Bash(xcrun *)",
      "Bash(instruments *)",
      "Bash(simctl *)",
      "Bash(adb *)",
      "Bash(emulator *)",
      "Bash(sdkmanager *)",
      "Bash(avdmanager *)",
      "Bash(gradlew *)",
      "Bash(aapt *)",
      "Bash(apktool *)",
      "Bash(dex2jar *)",
      "Bash(jarsigner *)",
      "Bash(keytool *)",
      "Bash(zipalign *)",
      "Bash(bundletool *)",
      "Bash(true)",
      "Bash(false)",
      "Bash(exit)",
      "Bash(top *)",
      "Bash(htop *)",
      "Bash(killall *)"
    ],
    "deny": [
      "Bash(rm -rf /)",
      "Bash(rm -rf /*)",
      "Bash(rm -rf ~)",
      "Bash(rm -rf ~/)",
      "Bash(rm -rf .)",
      "Bash(rm -rf ..)",
      "Bash(dd if=/dev/zero of=/dev/*)",
      "Bash(mkfs *)",
      "Bash(> /dev/sda)",
      "Bash(curl * | bash)",
      "Bash(curl * | sh)",
      "Bash(wget * | bash)",
      "Bash(wget * | sh)",
      "Bash(eval *)",
      "Bash(:(){:|:&};:)",
      "Bash(* > /dev/null 2>&1 &)"
    ]
  }
}
EOF

echo "✅ User-level settings created at ~/.claude/settings.json"

# Validate the JSON
if jq . ~/.claude/settings.json > /dev/null 2>&1; then
    echo "✅ JSON validation passed"
else
    echo "❌ JSON validation failed. Please check the file."
    exit 1
fi

echo ""
echo "📝 Next steps:"
echo "1. Restart Claude Code for the settings to take effect"
echo "2. Test with commands like: curl --version"
echo ""
echo "🎉 Setup complete! Your permissions are now configured at the user level."