// This file is automatically generated. Do not edit it directly.
// NOTE: The safeStorage import is a manual addition for Safari compatibility
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { safeStorage, validateSupabaseAuthToken, clearSupabaseAuthData } from '@/utils/safeStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate required environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing Supabase environment variables. ' +
    'Please configure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY environment variables.'
  );
}

// Validate auth token before initializing Supabase client
// This prevents white screen crashes in Safari when localStorage is corrupted
if (!validateSupabaseAuthToken()) {
  console.warn('🔧 Corrupted Supabase auth token detected, clearing auth data...');
  clearSupabaseAuthData();
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Use safeStorage wrapper instead of raw localStorage
    // This gracefully handles corrupted data that can cause Safari crashes
    storage: safeStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});